import {cloud,currentUser,listProjects,message,escapeHTML as esc} from './cloud.js';
import {systems,scenarios} from './data.js';
const main=document.querySelector('#account-main');
const raw=new URLSearchParams(location.search).get('return');
const returnTo=raw&&/^\/lab(?:\?|$)/.test(raw)?raw:null;
function status(text){const el=document.querySelector('#account-status');if(el)el.textContent=text;}
function login(){main.innerHTML=`<div class="account-auth"><section class="account-story"><span class="eyebrow">IL TUO LABORATORIO DIDATTICO</span><h1>Le tue prove.<br>Un motore alla volta.</h1><p>Conserva le configurazioni e le osservazioni delle esercitazioni. Riprendile in classe, anche da un altro dispositivo.</p><img src="/marketing/hero-combustion.webp" alt="Illustrazione di un motore in sezione"><p>Motori a benzina, ibridi ed elettrici.<br>Le tue esplorazioni in un unico archivio.</p></section><section class="account-form-card"><span class="eyebrow">ENGINELAB / AREA PERSONALE</span><h2>Bentornato.</h2><p>Accedi per salvare e riaprire le tue prove.</p><form id="login-form"><label>Nome utente<input name="username" autocomplete="username" required maxlength="254" placeholder="Il tuo nome utente"></label><label>Password<input name="password" type="password" autocomplete="current-password" required maxlength="128"></label><button class="button" type="submit">Accedi →</button></form><p id="account-status" role="status"></p><a href="/lab">Continua senza accedere ↗</a><small>Puoi esplorare liberamente il laboratorio. L’accesso serve per conservare le prove nell’archivio online.</small></section></div>`;
 document.querySelector('#login-form').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;status('Accesso in corso…');try{const f=new FormData(e.target),username=String(f.get('username')).trim();const {error}=await cloud.auth.signInWithPassword({email:username.toLowerCase()==='redazione'?'redazione@example.invalid':username,password:String(f.get('password'))});if(error)throw error;e.target.reset();if(returnTo)location.assign(returnTo);else await archive();}catch(error){status(message(error));button.disabled=false;}};
}
async function archive(){const user=await currentUser();if(!user)return login();main.innerHTML=`<section class="archive-heading"><div><span class="eyebrow">IL TUO ARCHIVIO PERSONALE</span><h1>Le mie prove</h1><p>Configurazioni e osservazioni per continuare il lavoro sui motori.</p></div><a class="button" href="/lab">+ Nuova prova</a></section><div class="account-toolbar"><span>${esc(user.email==='redazione@example.invalid'?'redazione':user.email)}</span><button id="logout">Esci dall’account</button></div><div class="archive-local"><div><b>Un esperimento da conservare?</b><p>Nel laboratorio scegli “Salva prova”, assegna un nome e annota ciò che hai osservato.</p></div><a href="/lab">Apri il laboratorio ↗</a></div><div class="archive-controls"><h2>Prove salvate</h2><label>Cerca una prova<input id="search" type="search" placeholder="Nome della prova"></label></div><p id="account-status" role="status">Caricamento delle prove…</p><div id="project-grid"></div>`;
 document.querySelector('#logout').onclick=async()=>{const {error}=await cloud.auth.signOut({scope:'local'});if(error)return status(message(error));login();};
 try{const projects=await listProjects();const render=()=>{const q=document.querySelector('#search').value.toLocaleLowerCase('it');const rows=projects.filter(p=>p.name.toLocaleLowerCase('it').includes(q));document.querySelector('#project-grid').innerHTML=rows.map(p=>{const s=p.document.settings,sys=systems[s.type];return `<article class="project-card"><div class="project-system">${esc(sys?.name||'Prova motore')}</div><div><h3>${esc(p.name)}</h3><p class="project-conditions">${esc(s.speed)} km/h · carico ${esc(s.load)}%<br>${esc(scenarios[s.scenario]?.name||'')}</p><p>Salvata il ${esc(new Date(p.updated_at).toLocaleString('it-IT',{dateStyle:'medium',timeStyle:'short'}))}</p><a href="/lab?project=${encodeURIComponent(p.id)}">Apri prova ↗</a></div></article>`;}).join('');status(projects.length?`${rows.length} ${rows.length===1?'prova':'prove'}`:'Il tuo archivio è pronto. Salva la prima prova dal laboratorio.');};document.querySelector('#search').oninput=render;render();}catch(error){status(message(error));}
}
try{if(await currentUser())await archive();else login();}catch{login();status('Connessione non disponibile. Riprova tra poco.');}
