// Plain-language reading keys use the same numbered anchors as the technical plates.
export const componentGuides={
 cover:{purpose:'È il coperchio superiore del motore: trattiene l’olio e protegge i meccanismi delle valvole.',labels:['Il guscio protegge i meccanismi','Il separatore trattiene le gocce d’olio','La guarnizione impedisce le perdite']},
 head:{purpose:'È la parte alta del motore. Fa entrare aria, accende la miscela e lascia uscire i gas bruciati.',labels:['Camme e molle aprono e chiudono le valvole','I passaggi guidano aria e gas','La candela produce la scintilla']},
 pistons:{purpose:'Sono spinti dai gas della combustione. Salgono e scendono nei cilindri per mettere in movimento l’albero motore.',labels:['La parte superiore riceve la spinta dei gas','Gli anelli impediscono ai gas di sfuggire','Il perno collega il pistone alla biella']},
 rods:{purpose:'Collegano i pistoni all’albero motore, come il collegamento tra un pedale e la sua manovella.',labels:['Il foro piccolo si collega al pistone','Il corpo centrale trasmette la spinta','Il foro grande abbraccia l’albero motore']},
 crank:{purpose:'Trasforma il movimento su e giù dei pistoni in una rotazione che può arrivare alle ruote.',labels:['Questi perni sostengono l’albero','I perni spostati dal centro ricevono la spinta','I canali portano olio alle superfici']},
 block:{purpose:'È la struttura portante del motore. Contiene i cilindri in cui scorrono i pistoni.',labels:['I cilindri guidano i pistoni','Il liquido attorno ai cilindri porta via calore','I supporti tengono l’albero nella posizione corretta']},
 intake:{purpose:'È un insieme di tubi che distribuisce l’aria ai cilindri prima della combustione.',labels:['La farfalla è una valvola che dosa l’aria','Il volume comune raccoglie l’aria in ingresso','Ogni ramo porta aria a un cilindro']},
 exhaust:{purpose:'Raccoglie i gas già bruciati e li porta verso il sistema di scarico.',labels:['Il bordo collega i tubi al motore','I rami raccolgono i gas caldi','L’uscita porta i gas verso il catalizzatore']},
 timing:{purpose:'Fa aprire le valvole al momento giusto, tenendole sincronizzate con i pistoni.',labels:['Le ruote grandi comandano le valvole','Cinghia o catena collegano le ruote','La ruota piccola riceve il moto dall’albero']},
 sump:{purpose:'È il serbatoio dell’olio sotto il motore. L’olio aiuta le parti a scorrere senza rovinarsi.',labels:['Le pareti interne limitano gli spostamenti dell’olio','Il tubo aspira l’olio attraverso un filtro','L’olio si raccoglie sul fondo della vasca']},
 housing:{purpose:'È il guscio del motore elettrico: protegge le parti e aiuta a raffreddarle.',labels:['Il guscio mantiene le parti allineate','Nei passaggi scorre il liquido refrigerante','Questa sede sostiene il cuscinetto']},
 stator:{purpose:'È la parte che resta ferma. La corrente nei fili di rame crea il campo magnetico che fa girare il rotore.',labels:['Sottili fogli di acciaio guidano il campo magnetico','Le bobine di rame ricevono la corrente','Un piccolo spazio separa statore e rotore']},
 rotor:{purpose:'È la parte che gira dentro il motore elettrico. I magneti seguono il campo creato dallo statore.',labels:['I magneti hanno poli nord e sud alternati','Il nucleo sostiene i magneti','Il foro centrale collega il rotore all’albero']},
 motor:{purpose:'Aiuta a muovere l’auto usando elettricità. In frenata può recuperare energia e ricaricare la batteria.',labels:['La parte esterna contiene le bobine fisse','La parte interna gira con l’albero','Un piccolo spazio evita il contatto tra le parti']},
 shaft:{purpose:'È l’asta metallica che porta la rotazione del motore agli ingranaggi della trasmissione.',labels:['I denti alle estremità agganciano gli altri pezzi','I gradini tengono i pezzi nella giusta posizione','La linea centrale indica l’asse di rotazione']},
 bearings:{purpose:'Permettono all’albero di girare con poco attrito. Le sfere rotolano tra due anelli.',labels:['L’anello esterno resta nel guscio','Le sfere rotolano e sono tenute distanziate','L’anello interno gira insieme all’albero']},
 inverter:{purpose:'Trasforma l’elettricità della batteria nel tipo di corrente necessario al motore e ne controlla l’erogazione.',labels:['Gli interruttori elettronici dosano la corrente','Il collegamento riceve energia dalla batteria','La base porta via il calore dell’elettronica']},
 battery:{purpose:'Conserva l’energia elettrica per il motore. È composta da molte piccole celle collegate tra loro.',labels:['Le celle sono riunite in gruppi chiamati moduli','I collegamenti e il controllo gestiscono le celle','La piastra mantiene uniforme la temperatura']},
 reducer:{purpose:'Riduce i giri del motore e aumenta la forza di rotazione disponibile alle ruote.',labels:['L’ingranaggio piccolo gira velocemente','Gli ingranaggi intermedi trasferiscono il moto','L’ingranaggio finale gira più lentamente']},
 transmission:{purpose:'Nell’ibrido rappresentato combina la spinta del motore a benzina con quella del motore elettrico.',labels:['Da qui arriva la spinta del motore a benzina','Il motore elettrico aggiunge la propria spinta','Gli ingranaggi portano il movimento alle ruote']}
};
