export const systems = {
  ice: { name: 'Motore a benzina', short: 'Termico', tag: 'COMBUSTIONE INTERNA', subtitle: '4 cilindri in linea · ciclo Otto · 2,0 L', icon: 'fuel', color: '#678b89', nominal: 110, maxRpm: 6500, components: ['cover','head','pistons','rods','crank','block','intake','exhaust','timing','sump'] },
  hybrid: { name: 'Sistema full hybrid', short: 'Ibrido', tag: 'DUE FONTI, UN SISTEMA', subtitle: 'Architettura parallela · termico + elettrico', icon: 'combine', color: '#8eac60', nominal: 130, maxRpm: 6000, components: ['cover','head','pistons','rods','crank','block','intake','exhaust','timing','sump','motor','inverter','battery','transmission'] },
  ev: { name: 'Motore elettrico', short: 'Elettrico', tag: 'TRAZIONE ELETTRICA', subtitle: 'Sincrono a magneti permanenti · batteria 400 V', icon: 'zap', color: '#8098c9', nominal: 150, maxRpm: 14000, components: ['housing','stator','rotor','shaft','bearings','inverter','battery','reducer'] }
};
export const components = {
 cover: { name: 'Coperchio punterie', category: 'Protezione', material: 'Lega di alluminio', description: 'Chiude la parte superiore della testata e contiene gli spruzzi di olio della distribuzione.', relationship: 'È fissato alla testata tramite una guarnizione. Protegge gli organi di distribuzione.', risk: 'Una guarnizione deteriorata può causare perdite di olio.', color: '#647b76', point: 'La tenuta dell’olio dipende anche dalle guarnizioni, non soltanto dalle parti in movimento.' },
 head: { name: 'Testata e valvole', category: 'Distribuzione', material: 'Alluminio e acciaio', description: 'Le valvole regolano l’ingresso della miscela e l’uscita dei gas. Le candele avviano la combustione nei cilindri.', relationship: 'La testata chiude i cilindri. Le valvole sono sincronizzate con l’albero motore.', risk: 'Temperature elevate possono deformare la testata e danneggiare la guarnizione.', color: '#a8b6b1', point: 'Aspirazione, compressione, espansione e scarico richiedono due giri dell’albero motore.' },
 pistons: { name: 'Pistoni', category: 'Organi in movimento', material: 'Lega di alluminio', description: 'Ricevono la pressione dei gas di combustione e si muovono alternativamente all’interno dei cilindri.', relationship: 'Trasmettono la forza alle bielle. Le fasce elastiche assicurano tenuta e controllo dell’olio.', risk: 'Scarsa lubrificazione e surriscaldamento possono causare rigature e grippaggio.', color: '#c1ccd0', point: 'La forma del cielo del pistone contribuisce alla geometria della camera di combustione.' },
 rods: { name: 'Bielle', category: 'Organi in movimento', material: 'Acciaio forgiato', description: 'Collegano i pistoni ai perni di manovella dell’albero motore, trasmettendo le forze di combustione.', relationship: 'Insieme all’albero motore trasformano il moto alternativo in rotazione.', risk: 'Le bronzine soffrono quando manca il film lubrificante.', color: '#a5adb1', point: 'La biella oscilla: non è un elemento che si muove soltanto in verticale.' },
 crank: { name: 'Albero motore', category: 'Trasmissione del moto', material: 'Acciaio forgiato', description: 'Trasforma, con le bielle, il movimento dei pistoni in coppia rotante disponibile alla trasmissione.', relationship: 'I contrappesi bilanciano parte delle forze. I supporti sono alloggiati nel basamento.', risk: 'Usura dei cuscinetti e lubrificazione insufficiente possono danneggiare i perni.', color: '#788792', point: 'La potenza dipende sia dalla coppia sia dalla velocità di rotazione: P = T · ω.' },
 block: { name: 'Basamento e cilindri', category: 'Struttura', material: 'Lega di alluminio', description: 'Sostiene gli organi principali e guida i pistoni. I passaggi interni permettono la circolazione di olio e refrigerante.', relationship: 'Collega testata, supporti dell’albero e coppa dell’olio in un’unica struttura.', risk: 'Il raffreddamento insufficiente può provocare dilatazioni eccessive e danni alle superfici.', color: '#8b9ba1', point: 'Il modello in sezione permette di vedere organi normalmente nascosti dal basamento.' },
 intake: { name: 'Collettore di aspirazione', category: 'Flusso d’aria', material: 'Polimero tecnico', description: 'Distribuisce l’aria ai cilindri. Nei motori a benzina la farfalla contribuisce a regolare il carico.', relationship: 'Collega il circuito di aspirazione alle valvole nella testata.', risk: 'Perdite di tenuta o depositi possono alterare il riempimento dei cilindri.', color: '#52666c', point: 'Il carico esprime la richiesta di coppia, mentre il regime indica i giri al minuto.' },
 exhaust: { name: 'Collettore di scarico', category: 'Gas di scarico', material: 'Acciaio resistente al calore', description: 'Convoglia i gas combusti verso il sistema di trattamento e lo scarico.', relationship: 'Riceve i gas dalle valvole di scarico. A valle si trova il catalizzatore, non rappresentato.', risk: 'È sottoposto a forti cicli termici, che possono favorire cricche e perdite.', color: '#b58b68', point: 'La temperatura dei gas di scarico è diversa da quella del liquido refrigerante.' },
 timing: { name: 'Distribuzione', category: 'Sincronizzazione', material: 'Acciaio', description: 'Mantiene sincronizzati albero motore e alberi a camme tramite una trasmissione meccanica.', relationship: 'In un quattro tempi gli alberi a camme ruotano a metà del regime dell’albero motore.', risk: 'Usura o perdita di fasatura possono compromettere il funzionamento e causare contatti tra organi.', color: '#879292', point: 'La fasatura stabilisce quando le valvole si aprono e si chiudono.' },
 sump: { name: 'Coppa dell’olio', category: 'Lubrificazione', material: 'Lega di alluminio', description: 'Raccoglie l’olio che viene rimesso in circolo dalla pompa per lubrificare e contribuire a raffreddare gli organi.', relationship: 'L’olio raggiunge cuscinetti, distribuzione e superfici in movimento.', risk: 'Un livello troppo basso può interrompere la corretta alimentazione del circuito.', color: '#697e7c', point: 'Lubrificazione e raffreddamento collaborano ma sono circuiti con funzioni diverse.' },
 motor: { name: 'Motogeneratore', category: 'Conversione elettrica', material: 'Rame, acciaio e magneti', description: 'Converte energia elettrica in coppia. In frenata può funzionare da generatore e recuperare una parte dell’energia cinetica.', relationship: 'L’inverter gestisce le correnti; la batteria accumula l’energia recuperata.', risk: 'Correnti elevate producono calore negli avvolgimenti e richiedono un adeguato raffreddamento.', color: '#b48c62', point: 'La frenata rigenerativa recupera solo una parte dell’energia e dipende anche dallo stato della batteria.' },
 inverter: { name: 'Inverter', category: 'Elettronica di potenza', material: 'Semiconduttori e alluminio', description: 'Converte la corrente continua della batteria in correnti alternate controllate per il motore.', relationship: 'Gestisce lo scambio bidirezionale di energia tra motore e batteria.', risk: 'Il surriscaldamento dei semiconduttori può portare a una riduzione della potenza.', color: '#9daea3', point: 'L’inverter controlla frequenza e ampiezza delle correnti, quindi coppia e velocità del motore.' },
 battery: { name: 'Batteria di trazione', category: 'Accumulo di energia', material: 'Celle agli ioni di litio', description: 'Immagazzina energia elettrica. Un sistema di gestione controlla tensioni, temperature e stato di carica delle celle.', relationship: 'Alimenta l’inverter. Nell’ibrido non plug-in si ricarica con recupero e motore termico.', risk: 'Temperature elevate accelerano il degrado. Il sistema di gestione può limitare potenza e ricarica.', color: '#87a575', point: 'Zero emissioni allo scarico non significa zero emissioni lungo l’intero ciclo di vita.' },
 transmission: { name: 'Trasmissione ibrida', category: 'Trasmissione del moto', material: 'Acciaio e alluminio', description: 'Nell’architettura parallela rappresentata combina il contributo del motore termico con quello elettrico.', relationship: 'Trasferisce la coppia dei due motori alla trasmissione finale.', risk: 'Lubrificazione e gestione della temperatura sono importanti anche nella trasmissione.', color: '#8a989e', point: 'Esistono anche ibridi in serie e a ripartizione di potenza: questo è un esempio parallelo semplificato.' },
 housing: { name: 'Carter motore', category: 'Struttura e raffreddamento', material: 'Lega di alluminio', description: 'Protegge e sostiene statore, rotore e cuscinetti; favorisce lo smaltimento del calore.', relationship: 'Lo statore è fissato al carter, mentre il rotore gira al suo interno.', risk: 'Problemi al circuito di raffreddamento possono aumentare la temperatura di esercizio.', color: '#8e9fa4', point: 'La struttura esterna resta ferma: è il rotore interno a ruotare.' },
 stator: { name: 'Statore e avvolgimenti', category: 'Campo magnetico', material: 'Rame e lamierini di acciaio', description: 'Gli avvolgimenti alimentati dall’inverter generano un campo magnetico rotante.', relationship: 'Il campo interagisce con i magneti del rotore per produrre coppia.', risk: 'Le perdite per effetto Joule scaldano gli avvolgimenti e possono degradare l’isolamento.', color: '#be8555', point: 'Le perdite nel rame aumentano con il quadrato della corrente: P = R · I².' },
 rotor: { name: 'Rotore a magneti', category: 'Organi in movimento', material: 'Acciaio e magneti permanenti', description: 'Ruota seguendo il campo magnetico dello statore e trasferisce coppia all’albero.', relationship: 'È separato dallo statore da un piccolo traferro, senza contatto tra le due parti.', risk: 'Temperature eccessive possono alterare le proprietà dei magneti.', color: '#96a8b0', point: 'In una macchina sincrona la velocità del rotore è legata alla frequenza elettrica e al numero di poli.' },
 shaft: { name: 'Albero di trasmissione', category: 'Trasmissione del moto', material: 'Acciaio', description: 'Trasferisce la coppia generata dal rotore al riduttore.', relationship: 'È sostenuto dai cuscinetti e solidale al rotore.', risk: 'Disallineamento e vibrazioni possono aumentare le sollecitazioni.', color: '#b7c3c7', point: 'Un riduttore abbassa la velocità e aumenta la coppia disponibile, al netto delle perdite.' },
 bearings: { name: 'Cuscinetti', category: 'Supporto e attrito', material: 'Acciaio', description: 'Sostengono l’albero e consentono la rotazione con attrito ridotto.', relationship: 'Collegano meccanicamente albero rotante e carter fisso.', risk: 'Usura e lubrificazione inadeguata possono causare rumore, attrito e vibrazioni.', color: '#a4afb1', point: 'Anche un motore elettrico contiene parti meccaniche soggette a usura.' },
 reducer: { name: 'Riduttore', category: 'Trasmissione del moto', material: 'Acciaio', description: 'Adatta la velocità elevata del motore elettrico alla velocità richiesta alle ruote.', relationship: 'Riceve la coppia dall’albero e la trasmette al differenziale, non rappresentato.', risk: 'Gli ingranaggi richiedono lubrificazione e possono usurarsi.', color: '#80908f', point: 'Un rapporto di riduzione fisso può coprire un ampio intervallo di velocità del veicolo.' }
};
export const scenarios = {
 city: { name: 'Città', speed: 30, demand: 9, rpm: 1800, load: 35, ambient: 20 },
 mixed: { name: 'Extraurbano', speed: 70, demand: 14, rpm: 2800, load: 50, ambient: 20 },
 highway: { name: 'Autostrada', speed: 120, demand: 21, rpm: 3800, load: 70, ambient: 25 },
 climb: { name: 'Salita impegnativa', speed: 50, demand: 30, rpm: 4500, load: 90, ambient: 35 }
};
const clamp = (n, a, b) => Math.min(b, Math.max(a,n));
export function simulate(type, input) {
 const s = scenarios[input.scenario] || scenarios.mixed;
 const load = clamp(Number(input.load) || 0, 10, 100) / 100;
 const normalizedRpm = clamp(Number(input.rpm) || 0, 800, systems[type].maxRpm) / systems[type].maxRpm;
 const ambient = clamp(Number(input.ambient) || 0, -10, 45);
 const cooling = input.cooling !== false;
 const thermalPenalty = !cooling ? 0.07 : Math.max(0, ambient-30)*0.001;
 let efficiency = type === 'ev' ? 0.92 - 0.10*(load-0.6)**2 - 0.05*normalizedRpm - thermalPenalty : type === 'hybrid' ? 0.35 + 0.04*load - 0.04*(normalizedRpm-0.5)**2 - thermalPenalty : 0.22 + 0.13*load - 0.08*(normalizedRpm-0.5)**2 - thermalPenalty;
 efficiency = clamp(efficiency, 0.14, 0.95);
 const wheelEnergy = s.demand * (0.75+load*0.5) * (1+Math.max(0,20-ambient)*0.004);
 // Recupero incorporato soltanto nella domanda netta dei cicli con decelerazioni.
 const recovery = type === 'ice' ? 0 : input.scenario === 'city' ? 0.20 : input.scenario === 'mixed' ? 0.08 : 0.02;
 const energy = wheelEnergy * (1-recovery) / efficiency;
 const consumption = type === 'ev' ? energy : energy / 8.9;
 const co2 = type === 'ev' ? 0 : consumption*23.1;
 const temperature = type === 'ev' ? 35 + load*43 + ambient*0.3 + (!cooling ? 55 : 0) : 67 + load*27 + ambient*0.4 + (!cooling ? 48 : 0);
 const power = (input.rpm>0?1:0) * systems[type].nominal * load * Math.min(1, normalizedRpm*2.2) * (cooling ? 1 : .72);
 return { efficiency: efficiency*100, consumption, energy, co2, temperature, power, torque: input.rpm>0?power*9550/input.rpm:0, recovery: recovery*100, loss: 100-efficiency*100, warning: !cooling || temperature > (type === 'ev' ? 110 : 110) };
}
export const questions = [
 { question: 'Perché il pistone è collegato all’albero motore tramite una biella?', options: ['Per convertire il moto alternativo in rotazione', 'Per abbassare la temperatura dei gas', 'Per immagazzinare energia elettrica'], correct: 0, explanation: 'Il meccanismo biella-manovella trasforma il movimento alternativo del pistone in rotazione dell’albero.' },
 { question: 'In frenata rigenerativa, quale conversione avviene?', options: ['Energia chimica → calore', 'Energia cinetica → energia elettrica', 'Energia elettrica → combustibile'], correct: 1, explanation: 'Il motore funziona da generatore. Una parte dell’energia cinetica ritorna alla batteria; il recupero non è totale.' },
 { question: 'Un veicolo elettrico ha zero emissioni…', options: ['In ogni fase del ciclo di vita', 'Nella produzione della batteria', 'Di CO₂ allo scarico durante la marcia'], correct: 2, explanation: 'Le emissioni allo scarico sono nulle. Produzione di elettricità, costruzione e fine vita richiedono un’analisi distinta.' }
];
