import {currentUser,loadProject,saveProject,message,escapeHTML as esc,refreshAccess} from './cloud.js';
import {validateProject} from './project-document.js';
export async function mountLabAccount({capture,restore,modal}){
 let binding=null,name='La mia prova',notes='',busy=false,loadFailed=false;
 const status=document.createElement('small');status.id='project-status';status.setAttribute('role','status');document.querySelector('.page-heading>div').append(status);
 const save=document.createElement('button');save.className='outline-button save-project-button';save.textContent='Salva prova';save.id='save-project';document.querySelector('.page-heading').append(save);
 const route=new URL(location.href),id=route.searchParams.get('project');
 if(id){save.disabled=true;status.textContent='Apertura della prova…';try{const loaded=await loadProject(id);binding=loaded.binding;name=loaded.project.name;notes=loaded.project.notes;restore(loaded.project.settings);status.textContent=name+' · prova riaperta in pausa';}catch(error){loadFailed=true;status.textContent=message(error);modal('Prova non disponibile',`<p>${esc(message(error))}</p><a class="primary-button" href="/account?return=${encodeURIComponent(location.pathname+location.search)}">Accedi all’area personale</a><p><a href="/lab">Avvia una nuova prova</a></p>`);}finally{save.disabled=loadFailed;}}
 else if(route.searchParams.get('restore')==='1'){try{const saved=sessionStorage.getItem('enginelab-pending');if(saved){const p=validateProject(JSON.parse(saved));restore(p.settings);name=p.name;notes=p.notes;status.textContent='Configurazione ripristinata · scegli Salva prova';sessionStorage.removeItem('enginelab-pending');}}catch{status.textContent='La configurazione precedente non è disponibile.';}}
 save.onclick=()=>{if(loadFailed)return;modal('Salva la tua prova',`<form id="project-form"><label>Nome della prova<input name="name" required maxlength="100" value="${esc(name)}"></label><label>Le tue osservazioni<textarea name="notes" maxlength="2000" rows="4" placeholder="Che cosa hai modificato? Che cosa hai osservato?">${esc(notes)}</textarea></label><p class="project-save-hint">Conserva propulsore, condizioni operative, vista esplosa, posizione dei pezzi e note. Alla riapertura riparte in pausa; i contatori della prova ripartono da zero.</p><div class="project-save-actions"><button class="primary-button" type="submit">${binding?'Aggiorna prova':'Salva online'}</button>${binding?'<button class="outline-button" type="submit" name="copy" value="1">Salva una copia</button>':''}</div><p id="save-status" role="status"></p></form>`,'AREA PERSONALE');
  document.querySelector('#project-form').onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;const form=e.target,feedback=form.querySelector('#save-status'),buttons=[...form.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);const f=new FormData(form);name=String(f.get('name')).trim();notes=String(f.get('notes'));try{const p=validateProject({version:1,name,notes,settings:capture()});if(!await currentUser()){sessionStorage.setItem('enginelab-pending',JSON.stringify(p));location.assign('/account?return='+encodeURIComponent('/lab?restore=1'));return;}feedback.textContent='Salvataggio in corso…';const result=await saveProject(p,e.submitter?.name==='copy'?null:binding);binding=result;const u=new URL(location.href);u.search='';u.searchParams.set('project',result.id);history.replaceState(null,'',u);status.textContent=p.name+' · salvata online';feedback.textContent='Prova salvata. La trovi nella tua area personale.';}catch(error){feedback.textContent=message(error);}finally{busy=false;buttons.forEach(b=>b.disabled=false);}};
 };
 refreshAccess();
}
