import {co2PerLiter,gasolineKwhPerLiter,scenarios,systems} from './data.js';
import {wheelDiameter,ratios,roadMotion} from './motion.js';
const f=(n,d=2)=>new Intl.NumberFormat('it-IT',{maximumFractionDigits:d}).format(n);
const sources=[
 ['EPA · Emissioni di un veicolo','https://www.epa.gov/greenvehicles/greenhouse-gas-emissions-typical-passenger-vehicle','Costante di riferimento',`EPA indica 8.887 g di CO₂ per gallone USA di benzina. Dividendo per 3,78541 L otteniamo circa ${f(co2PerLiter)} kg/L, valore arrotondato usato qui. La composizione del carburante può variare. La pagina distingue inoltre emissioni allo scarico ed emissioni a monte.`],
 ['DOE / AFDC · Proprietà dei carburanti','https://afdc.energy.gov/fuels/properties','Intervallo documentato',`Per benzina/E10, AFDC riporta un potere calorifico inferiore di 112.114–116.090 Btu/gal: circa 8,68–8,99 kWh/L. Il laboratorio adotta ${f(gasolineKwhPerLiter)} kWh/L come valore rappresentativo, non universale.`],
 ['NIST · Conversione dell’energia','https://www.nist.gov/glossary-term/19511','Conversioni', 'Riferimento per la conversione da Btu a joule: 1 Btu ≈ 1.055 J. Per esprimere l’energia in kWh si usa inoltre 1 kWh = 3,6 MJ.'],
 ['DOE / EPA · Dove va l’energia','https://www.fueleconomy.gov/feg/atv.shtml','Principi fisici', 'Descrive perdite termiche e meccaniche, resistenza al rotolamento, resistenza aerodinamica e recupero in frenata. Supporta le relazioni qualitative; i coefficienti di engineLab non sono presi da questo diagramma.'],
 ['DOE / AFDC · Come funziona un ibrido','https://afdc.energy.gov/vehicles/how-do-hybrid-electric-cars-work','Architettura e componenti','Riferimento per motore termico, motore elettrico, batteria e frenata rigenerativa. Il laboratorio rappresenta un’architettura parallela semplificata; non tutte le auto ibride hanno questa disposizione.'],
 ['DOE / AFDC · Come funziona un’elettrica','https://afdc.energy.gov/vehicles/how-do-all-electric-cars-work','Architettura e componenti','Riferimento per batteria, elettronica di potenza, motore di trazione e raffreddamento. La simulazione rappresenta una macchina sincrona a magneti permanenti, non tutte le possibili motorizzazioni.'],
 ['EPA · Inquinanti dei veicoli','https://www.epa.gov/greenvehicles/smog-vehicle-emissions','Limiti delle emissioni mostrate','CO₂ e inquinanti atmosferici non sono sinonimi. Qui calcoliamo solo la CO₂ allo scarico a partire dal carburante: non stimiamo CO, NOx, idrocarburi o particolato.']
];
document.querySelector('#reference-list').innerHTML=sources.map(([title,url,tag,text],i)=>`<article class="reference-card"><span>${String(i+1).padStart(2,'0')} / ${tag}</span><h3><a href="${url}" target="_blank" rel="noopener noreferrer">${title} ↗</a></h3><p>${text}</p></article>`).join('');
const formulas=[
 ['Energia in ingresso','E = D × (1 − recupero) ÷ rendimento','D è la domanda alle ruote in kWh/100 km. Recupero e rendimento sono frazioni, non percentuali intere.'],
 ['Consumo benzina',`C = E ÷ ${f(gasolineKwhPerLiter)} kWh/L`,'Il risultato è in L/100 km. Nell’elettrico E è già il consumo in kWh/100 km.'],
 ['Chilometri con un litro','km/L = 100 ÷ C','Definito solo per un consumo positivo e una velocità maggiore di zero.'],
 ['Litri ogni ora','L/h = C × km/h ÷ 100','Collega il consumo per distanza al consumo per tempo.'],
 ['CO₂ per chilometro',`g/km = C × ${f(co2PerLiter*10)}`,'Dal fattore kg/L a g/km, per un consumo C espresso in L/100 km.'],
 ['CO₂ ogni secondo',`g/s = L/h × ${f(co2PerLiter*1000,0)} ÷ 3.600`,'La CO₂ totale integra questo flusso nel tempo. Nell’elettrico la CO₂ allo scarico è zero.'],
 ['Potenza netta richiesta','kW = D × (1 − recupero) × km/h ÷ 100','È una media equivalente del percorso, distinta dalla potenza disponibile indicativa.'],
 ['Totali della prova','Distanza = ∫ velocità × dt / 3.600','Tempo in secondi; carburante ed energia si integrano allo stesso modo dalle rispettive portate.']
];
document.querySelector('#formula-rows').innerHTML=formulas.map(row=>`<tr>${row.map((x,i)=>i?`<td>${x}</td>`:`<th scope="row">${x}</th>`).join('')}</tr>`).join('');
document.querySelector('#motion-facts').innerHTML=`<article><span>Diametro di rotolamento</span><strong>${f(wheelDiameter)} m</strong><small>Ipotesi comune ai tre modelli</small></article><article><span>Rapporti totali fissi</span><strong>${ratios.ice}:1 / ${ratios.hybrid}:1 / ${ratios.ev}:1</strong><small>Termico / ibrido / elettrico · scelte didattiche</small></article>`;
document.querySelector('#motion-example').innerHTML=`<table><caption>Esempio calcolato a 100 km/h</caption><thead><tr><th>Sistema</th><th>Giri ruote/min</th><th>Giri motore/min</th></tr></thead><tbody>${Object.entries(systems).map(([id,s])=>{const m=roadMotion(id,100);return `<tr><th scope="row">${s.short}</th><td>${f(m.wheelRpm,0)}</td><td>${f(m.rpm,0)}</td></tr>`;}).join('')}</tbody></table>`;
document.querySelector('#scenario-rows').innerHTML=Object.values(scenarios).map(s=>`<tr><th scope="row">${s.name}</th><td>${s.speed} km/h</td><td>${s.demand} kWh/100 km</td><td>${s.load}%</td></tr>`).join('');
document.querySelector('#model-equations').innerHTML=`<p>l = carico / 100; r = rpm / regime massimo; a = temperatura ambiente; v = velocità; v₀ = velocità di riferimento dello scenario.</p><div class="formula-block">Fattore velocità = [0,55 + 0,45 × (v/70)²] / [0,55 + 0,45 × (v₀/70)²]<br>D = domanda scenario × fattore velocità × (0,75 + 0,5l) × [1 + 0,004 × max(0; 20 − a)]<br>Penalità termica p = 0,07 senza raffreddamento; altrimenti 0,001 × max(0; a − 30)<br>η termico = 0,22 + 0,13l − 0,08(r − 0,5)² − p<br>η ibrido = 0,35 + 0,04l − 0,04(r − 0,5)² − p<br>η elettrico = 0,92 − 0,10(l − 0,6)² − 0,05r − p</div><p>I rendimenti η sono limitati tra 0,14 e 0,95. Regimi massimi illustrativi: ${systems.ice.maxRpm}, ${systems.hybrid.maxRpm} e ${systems.ev.maxRpm} rpm. Il rapporto fisso sotto il regime di minimo è solo una rappresentazione cinematica: non modella frizione o cambio.</p><div class="formula-block">T equilibrio termico/ibrido = 67 + 27l + 0,4a + 48 se manca il raffreddamento<br>T equilibrio elettrico = 35 + 43l + 0,3a + 55 se manca il raffreddamento<br>T(t) = T equilibrio + (T iniziale − T equilibrio) × exp(−t / τ)<br>Fattore freddo = 1 + 0,15 × clamp[(70 − T) / 50; 0; 1]</div><p>Il fattore freddo moltiplica il consumo di benzina; il rendimento istantaneo viene diviso per lo stesso fattore. τ = 90 s in marcia, 180 s da fermo. Il confronto non applica il fattore freddo. La soglia di allerta di 110 °C è illustrativa e non sostituisce limiti del costruttore.</p><div class="formula-block">Potenza disponibile = nominale × l × min(1; 2,2r) × fattore termico<br>Coppia disponibile = potenza in kW × 60.000 / (2π × rpm)</div><p>Nominali illustrativi: ${systems.ice.nominal} / ${systems.hybrid.nominal} / ${systems.ev.nominal} kW. Fattore termico: 1 con raffreddamento, 0,72 senza. Potenza disponibile e coppia sono esempi separati dalla domanda alle ruote: non costituiscono una mappa prestazionale validata.</p>`;
